# Standards: 0.11
---
- name: Print the preflight parameterss
  ansible.builtin.debug:
    msg: Ansible Distribution  {{ ansible_distribution  }} has ansible_distribution_version {{ ansible_distribution_version  }} cis_target_os_versions {{ cis_target_os_versions }} cis_target_os_distribution {{ cis_target_os_distribution }}
    
- name: Preflight - Fail if host is not suitable for this benchmark
  fail:
    msg: "This benchmark is not suitable for the destination operating system"
  when: (ansible_distribution is not defined) or (ansible_distribution_version is not defined) or (ansible_distribution_version not in cis_target_os_versions) or (ansible_distribution != cis_target_os_distribution)
  tags: always